language: node_js
node_js: 
- 12.14.1
cache: npm

# before_install:
install:
  - npm ci
# before_script:
script:
  # - npm test
  - npm run build
# after_success:
# after_failure:
# after_script:
# before_deploy:
deploy:
  provider: surge
  skip-cleanup: true
  project: ./public/
  domain: rssviana-website.surge.sh
  on:
    branch: master
# after_deploy: