/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BytefotosRouteImport } from './routes/bytefotos'
import { Route as BytecodeRouteImport } from './routes/bytecode'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosIndexRouteImport } from './routes/artigos/index'
import { Route as ArtigosSlugRouteImport } from './routes/artigos/$slug'

const BytefotosRoute = BytefotosRouteImport.update({
  id: '/bytefotos',
  path: '/bytefotos',
  getParentRoute: () => rootRouteImport,
} as any)
const BytecodeRoute = BytecodeRouteImport.update({
  id: '/bytecode',
  path: '/bytecode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bytecode': typeof BytecodeRoute
  '/bytefotos': typeof BytefotosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bytecode': typeof BytecodeRoute
  '/bytefotos': typeof BytefotosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/artigos': typeof ArtigosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bytecode': typeof BytecodeRoute
  '/bytefotos': typeof BytefotosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bytecode' | '/bytefotos' | '/artigos/$slug' | '/artigos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bytecode' | '/bytefotos' | '/artigos/$slug' | '/artigos'
  id:
    | '__root__'
    | '/'
    | '/bytecode'
    | '/bytefotos'
    | '/artigos/$slug'
    | '/artigos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BytecodeRoute: typeof BytecodeRoute
  BytefotosRoute: typeof BytefotosRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bytefotos': {
      id: '/bytefotos'
      path: '/bytefotos'
      fullPath: '/bytefotos'
      preLoaderRoute: typeof BytefotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bytecode': {
      id: '/bytecode'
      path: '/bytecode'
      fullPath: '/bytecode'
      preLoaderRoute: typeof BytecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BytecodeRoute: BytecodeRoute,
  BytefotosRoute: BytefotosRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
